### ISSUE TITLE
Not add in firefox

### ISSUE THREAD

**Issue by monikasharma47** [SeifElsallamy/Blind-XSS-Manager#1]
This extension is not add in firefox

**Comment by jakre1234** [comment]
Because it's Chrome extension :1st_place_medal: 
The first line of the ReadMe states that :|
```
A Chrome extension that keeps track of the injected urls with Blind XSS payloads.
```

**Comment by SeifElsallamy** [comment]
Hi @monikasharma47,
Thank you for mentioning that.
I understand that many security researchers are using Firefox so they need such plugin there. However, I am not familiar with Firefox plugins and currently I don't have the time to develop that. You do have the source code of the Chrome extension so you might try to develop one which is suitable to Firefox using this source code. Feel free to message me whenever you need help.
All the best!
Seif
